name: CI Test

on: [ push, pull_request ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        use-metall: ["ON","OFF"]
    steps:
      - &checkout
        uses: actions/checkout@v4
      - &install_openmpi
        name: Install OpenMPI
        run: sudo apt-get install openmpi-bin libopenmpi-dev
      - name: Build
        run: |
          mkdir build && cd build
          cmake ../ -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_CXX_COMPILER=g++-12 -DSALTATLAS_USE_METALL=${{ matrix.use-metall }} -DSALTATLAS_USE_HNSWLIB=ON -DSALTATLAS_BUILD_TEST=ON
          make -j4
      - name: Test
        run: |
          cd build
          ./test/common/test_data_reader_kernel
          mpirun -np 1 ./test/common/test_data_reader 
          mpirun -np 2 ./test/common/test_data_reader 

  build-just-install:
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *install_openmpi
      - name: Just install
        run: |
          mkdir build && cd build
          cmake ../ -DCMAKE_CXX_COMPILER=g++-12 -DJUST_INSTALL_SALTATLAS=ON -DSALTATLAS_USE_METALL=ON -DSALTATLAS_USE_HNSWLIB=ON
          make -j4